apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mongo.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  type: {{ .Values.services.mongo.type }}
  selector:
    app: {{ .Values.app }}
  ports:
    - name: mongodb
      port: {{ .Values.services.mongo.port }}
      targetPort: {{ .Values.database.mongo.port }}
