# Secret (use secure methods for production secrets)
apiVersion: v1
kind: Secret
metadata:
  name: nodegoat-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  cookieSecret: "CHANGE_ME_cookie_secret"
  cryptoKey: "CHANGE_ME_crypto_key"