# Secret (ใช้ stringData เปลี่ยนค่าให้ปลอดภัยก่อนใช้)
apiVersion: v1
kind: Secret
metadata:
  name: nodegoat-secret
  namespace: nodegoat1
type: Opaque
stringData:
  cookieSecret: "CHANGE_ME_cookie_secret"
  cryptoKey: "CHANGE_ME_crypto_key"