apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat
  namespace: nodegoat1
spec:
  replicas: 2
  selector: { matchLabels: { app: nodegoat } }
  template:
    metadata: { labels: { app: nodegoat } }
    spec:
      containers:
        - name: nodegoat
          image: nodegoat:local
          imagePullPolicy: IfNotPresent
          command: [ "npm", "start" ]
          ports: [{ containerPort: 4000 }]
          envFrom:
            - configMapRef: { name: nodegoat-config }
          env:
            - name: NODE_ENV
              value: "development"
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef: { name: nodegoat-secret, key: cookieSecret }
          livenessProbe:
            httpGet: { path: "/", port: 4000 }
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: "/", port: 4000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
