name: Runner Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: [self-hosted, docker-desktop]

    steps:
      - name: Basic test
        run: |
          echo "Runner started"
          whoami
          hostname